#' Self-regulated-learning (MSLQ) construct scores simulated by large language models
#'
#' Five data sets of Motivated Strategies for Learning Questionnaire (MSLQ)
#' construct scores, each a random sample of 300 cases generated by one large
#' language model in the study *"Delving into the psychology of Machines:
#' Exploring the structure of self-regulated learning via LLM-generated survey
#' responses"* (Computers in Human Behavior, 2025). One data set per model:
#' `SRL_GPT`, `SRL_Gemini`, `SRL_Claude`, `SRL_Mistral`, and `SRL_LLaMa`.
#'
#' Only the five models whose responses carry estimable structure are included.
#' Two other generators from the original study (ChatGPT and LeChat) produced
#' near-independent items (mean absolute inter-item correlation
#' \eqn{\approx 0.03}), so their network is the empty graph; they are omitted.
#' The five retained models span the spectrum the paper describes, from
#' realistically structured (`SRL_GPT`) to strongly "over-coherent"
#' (`SRL_Gemini`, `SRL_Claude`).
#'
#' @format Each is a data frame with 300 rows and 5 variables -- the MSLQ
#'   construct scores (each the mean of that construct's Likert items, range
#'   1--7):
#' \describe{
#'   \item{`CSU`}{cognitive strategy use}
#'   \item{`IV`}{intrinsic value}
#'   \item{`SE`}{self-efficacy}
#'   \item{`SR`}{self-regulation}
#'   \item{`TA`}{test anxiety}
#' }
#' @source *Delving into the psychology of Machines: Exploring the structure of
#'   self-regulated learning via LLM-generated survey responses.* Computers in
#'   Human Behavior (2025).
#'   <https://www.sciencedirect.com/science/article/pii/S074756322500216X>
#' @examples
#' # partial-correlation network of the five constructs for one model
#' net <- ebic_glasso(SRL_GPT)
#' net_centralities(net)
#'
#' # compare two models' construct networks
#' net_compare(SRL_GPT, SRL_Claude, iter = 200)
#' @name SRL
#' @keywords datasets
"SRL_GPT"

#' @rdname SRL
#' @format NULL
"SRL_Gemini"

#' @rdname SRL
#' @format NULL
"SRL_Claude"

#' @rdname SRL
#' @format NULL
"SRL_Mistral"

#' @rdname SRL
#' @format NULL
"SRL_LLaMa"
